broadcast:
  enabled: true
command:
  enabled: false
  strings:
    - 'msg %player% Nice Find :D'
    - 'say Hello'
signs:
  enabled: true
  string: '[oresign]'
  cooldown: 3
  line0: '&m----------'
  line1: '&aOre Stats'
  line2: 'Right Click!'
  line3: '&m----------'
reward:
  enabled: false
  mult: 2