broadcast:
  enabled: true
command:
  enabled: true
  string: 'msg %player% Nice Find :D'
signs:
  enabled: true
  string: '[oresign]'
  cooldown: 3
  line0: '&m----------'
  line1: '&aOre Stats'
  line2: 'Right Click!'
  line3: '&m----------'